import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practicesoftwaretesting.com/');
  await page.locator('[data-test="nav-sign-in"]').click();
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').fill('testmail73@gmail.com');
  await page.locator('[data-test="password"]').dblclick();
  await page.locator('[data-test="password"]').fill('TestTest123!!');
  await page.locator('[data-test="login-submit"]').click();
  await page.getByRole('link', { name: 'Practice Software Testing -' }).click();
  await page.locator('[data-test="product-01JFPWYKHGMMKG9ZC77F80MX3X"]').click();
  await page.locator('[data-test="add-to-cart"]').click();
  await page.getByLabel('Product added to shopping').click();
  await page.locator('[data-test="nav-cart"]').click();
  await page.locator('[data-test="proceed-1"]').click();
  await page.getByText('Hello Testname Testlastname,').click();
  await page.locator('div').filter({ hasText: 'Hello Testname Testlastname,' }).nth(4).click();
  await page.locator('[data-test="proceed-2"]').click();
  await page.locator('[data-test="proceed-3"]').click();
  await page.getByRole('heading', { name: 'Payment' }).click();
  await page.locator('[data-test="payment-method"]').selectOption('bank-transfer');
  await page.locator('[data-test="bank_name"]').click();
  await page.locator('[data-test="bank_name"]').fill('TestBank');
  await page.locator('[data-test="bank_name"]').press('Tab');
  await page.locator('[data-test="account_name"]').fill('TestAccountName');
  await page.locator('[data-test="account_number"]').fill('555565423123123');
  await page.locator('[data-test="finish"]').click();
  await page.getByText('Payment was successful').click();
  await page.locator('[data-test="finish"]').click();
  await page.getByText('Thanks for your order! Your').click();
});